# Generated by Django 4.0.5 on 2022-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=80, null=True)),
                ('date_of_publication', models.DateField(null=True)),
                ('number_pages', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('region', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('principal_name', models.CharField(max_length=80, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('school_id', models.IntegerField(null=True)),
                ('books_id', models.IntegerField(null=True)),
            ],
        ),
    ]
